---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: remark42
  namespace: remark42
  labels:
    app: remark42
stringData:
  EDIT_TIME: "43200m"
  ALLOWED_HOSTS: example.com
  REMARK_URL: https://remark42.example.com
  SECRET: YOUR RANDOM SECRET
  SITE: example.com

  SSL_PORT: 8443
  SSL_TYPE: static
  SSL_CERT: /etc/remark42/ssl/tls.crt
  SSL_KEY: /etc/remark42/ssl/tls.key

  AVATAR_TYPE: uri
  AVATAR_URI: "mongodb://user:password@mongo_host:27017/auth_database?tls=true&ava_db=storage_database"

  IMAGE_TYPE: rpc
  IMAGE_RPC_API: http://localhost:9000

  STORE_TYPE: rpc
  STORE_RPC_API: http://localhost:9000

  AUTH_FACEBOOK_CID: Your Facebook Client ID
  AUTH_FACEBOOK_CSEC: Your Facebook Client Secret

  AUTH_GITHUB_CID: Your Github Client ID
  AUTH_GITHUB_CSEC: Your Github Client Secret

  AUTH_TWITTER_CID: Your Twitter Client ID
  AUTH_TWITTER_CSEC: Your Twitter Client Secret
