---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: remark42-cluster
  namespace: {{ namespace }}
  labels:
    app: remark42
    ansible-managed: "true"
stringData:
  DB_URL: "mongodb://user:password@mongo_host:27017/auth_database?tls=true&engine_db=storage_database"
  PORT: "9000"
  S3_ACCESS_KEY: Your S3 Access Key
  S3_BUCKET_NAME: Your S3 Bucket Name
  S3_REGION: Your S3 Region
  S3_SECRET: Your S3 Secret
  S3_ENDPOINT_URL: Your S3 Endpoint URL ie: Scaleway, OVH, AWS, etc
